// flow-typed signature: 964182d1bca9d62e414057d6f3aa23f6
// flow-typed version: <<STUB>>/babel-plugin-module-require_v^1.5.0/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-module-require'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-module-require' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-module-require/index.build' {
  declare module.exports: any;
}

declare module 'babel-plugin-module-require/index.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-module-require/index.build.js' {
  declare module.exports: $Exports<'babel-plugin-module-require/index.build'>;
}
declare module 'babel-plugin-module-require/index' {
  declare module.exports: $Exports<'babel-plugin-module-require'>;
}
declare module 'babel-plugin-module-require/index.js' {
  declare module.exports: $Exports<'babel-plugin-module-require'>;
}
declare module 'babel-plugin-module-require/index.test.js' {
  declare module.exports: $Exports<'babel-plugin-module-require/index.test'>;
}
