// flow-typed signature: 9d0cfb7e4bfbede1849a41910e65fddf
// flow-typed version: <<STUB>>/engine.io_v^3.1.0/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'engine.io'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'engine.io' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'engine.io/lib/engine.io' {
  declare module.exports: any;
}

declare module 'engine.io/lib/server' {
  declare module.exports: any;
}

declare module 'engine.io/lib/socket' {
  declare module.exports: any;
}

declare module 'engine.io/lib/transport' {
  declare module.exports: any;
}

declare module 'engine.io/lib/transports/index' {
  declare module.exports: any;
}

declare module 'engine.io/lib/transports/polling-jsonp' {
  declare module.exports: any;
}

declare module 'engine.io/lib/transports/polling-xhr' {
  declare module.exports: any;
}

declare module 'engine.io/lib/transports/polling' {
  declare module.exports: any;
}

declare module 'engine.io/lib/transports/websocket' {
  declare module.exports: any;
}

// Filename aliases
declare module 'engine.io/lib/engine.io.js' {
  declare module.exports: $Exports<'engine.io/lib/engine.io'>;
}
declare module 'engine.io/lib/server.js' {
  declare module.exports: $Exports<'engine.io/lib/server'>;
}
declare module 'engine.io/lib/socket.js' {
  declare module.exports: $Exports<'engine.io/lib/socket'>;
}
declare module 'engine.io/lib/transport.js' {
  declare module.exports: $Exports<'engine.io/lib/transport'>;
}
declare module 'engine.io/lib/transports/index.js' {
  declare module.exports: $Exports<'engine.io/lib/transports/index'>;
}
declare module 'engine.io/lib/transports/polling-jsonp.js' {
  declare module.exports: $Exports<'engine.io/lib/transports/polling-jsonp'>;
}
declare module 'engine.io/lib/transports/polling-xhr.js' {
  declare module.exports: $Exports<'engine.io/lib/transports/polling-xhr'>;
}
declare module 'engine.io/lib/transports/polling.js' {
  declare module.exports: $Exports<'engine.io/lib/transports/polling'>;
}
declare module 'engine.io/lib/transports/websocket.js' {
  declare module.exports: $Exports<'engine.io/lib/transports/websocket'>;
}
