// flow-typed signature: fa2f91c2a1eaa427034f566a53c2a730
// flow-typed version: <<STUB>>/eslint-config-marudor_v^5.0.0/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-marudor'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-marudor' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-config-marudor/noReact' {
  declare module.exports: any;
}

declare module 'eslint-config-marudor/rules/bestPractice' {
  declare module.exports: any;
}

declare module 'eslint-config-marudor/rules/classProperty' {
  declare module.exports: any;
}

declare module 'eslint-config-marudor/rules/errors' {
  declare module.exports: any;
}

declare module 'eslint-config-marudor/rules/es6' {
  declare module.exports: any;
}

declare module 'eslint-config-marudor/rules/flow' {
  declare module.exports: any;
}

declare module 'eslint-config-marudor/rules/header' {
  declare module.exports: any;
}

declare module 'eslint-config-marudor/rules/react' {
  declare module.exports: any;
}

declare module 'eslint-config-marudor/rules/sort' {
  declare module.exports: any;
}

declare module 'eslint-config-marudor/rules/stylistic' {
  declare module.exports: any;
}

declare module 'eslint-config-marudor/rules/variables' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-config-marudor/index' {
  declare module.exports: $Exports<'eslint-config-marudor'>;
}
declare module 'eslint-config-marudor/index.js' {
  declare module.exports: $Exports<'eslint-config-marudor'>;
}
declare module 'eslint-config-marudor/noReact.js' {
  declare module.exports: $Exports<'eslint-config-marudor/noReact'>;
}
declare module 'eslint-config-marudor/rules/bestPractice.js' {
  declare module.exports: $Exports<'eslint-config-marudor/rules/bestPractice'>;
}
declare module 'eslint-config-marudor/rules/classProperty.js' {
  declare module.exports: $Exports<'eslint-config-marudor/rules/classProperty'>;
}
declare module 'eslint-config-marudor/rules/errors.js' {
  declare module.exports: $Exports<'eslint-config-marudor/rules/errors'>;
}
declare module 'eslint-config-marudor/rules/es6.js' {
  declare module.exports: $Exports<'eslint-config-marudor/rules/es6'>;
}
declare module 'eslint-config-marudor/rules/flow.js' {
  declare module.exports: $Exports<'eslint-config-marudor/rules/flow'>;
}
declare module 'eslint-config-marudor/rules/header.js' {
  declare module.exports: $Exports<'eslint-config-marudor/rules/header'>;
}
declare module 'eslint-config-marudor/rules/react.js' {
  declare module.exports: $Exports<'eslint-config-marudor/rules/react'>;
}
declare module 'eslint-config-marudor/rules/sort.js' {
  declare module.exports: $Exports<'eslint-config-marudor/rules/sort'>;
}
declare module 'eslint-config-marudor/rules/stylistic.js' {
  declare module.exports: $Exports<'eslint-config-marudor/rules/stylistic'>;
}
declare module 'eslint-config-marudor/rules/variables.js' {
  declare module.exports: $Exports<'eslint-config-marudor/rules/variables'>;
}
