// flow-typed signature: 91177e98d5c3021a54b7c5d4b20a3115
// flow-typed version: <<STUB>>/password-hash_v1.2.2/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'password-hash'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'password-hash' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'password-hash/lib/password-hash' {
  declare module.exports: any;
}

declare module 'password-hash/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'password-hash/lib/password-hash.js' {
  declare module.exports: $Exports<'password-hash/lib/password-hash'>;
}
declare module 'password-hash/test/index.js' {
  declare module.exports: $Exports<'password-hash/test/index'>;
}
