// flow-typed signature: 538d01a3afb575a987d71c794f9b63b8
// flow-typed version: <<STUB>>/primus-emit_v^1.0.0/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'primus-emit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'primus-emit' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'primus-emit/broadcast' {
  declare module.exports: any;
}

// Filename aliases
declare module 'primus-emit/broadcast.js' {
  declare module.exports: $Exports<'primus-emit/broadcast'>;
}
declare module 'primus-emit/index' {
  declare module.exports: $Exports<'primus-emit'>;
}
declare module 'primus-emit/index.js' {
  declare module.exports: $Exports<'primus-emit'>;
}
